### ISSUE TITLE
Can't create queues on IPv6 hosts

### ISSUE THREAD

**Issue by jbruggem** [roq-messaging/RoQ#106]
Here's what happens:

```
============================================
roq> q c test 2001:470:0000:0000:0000:0000:fe7c:60b2%2
============================================

DEBUG [Timer-0] (RoQBSONSerializer.java:81) - { "Hosts" : [ "2001:470:0000:0000:0000:0000:fe7c:60b2%2"]}
DEBUG [Thread-2] (MngtController.java:276) - Create Q request ...
ERROR [Thread-2] (LogicalQFactory.java:122) - java.lang.IllegalStateException: the target address 2001:470:0000:0000:0000:0000:fe7c:60b2%2 is not registered as a node of the cluster (no Host manager running)
DEBUG [Thread-2] (RoQBSONSerializer.java:228) - { "RESULT" : 1101 , "COMMENT" : "ERROR when starting  queue, check logs of the logical queue factory"}
DEBUG [Thread-2] (MngtController.java:293) - Create queue name = test on 2001:470:0000:0000:0000:0000:fe7c:60b2%2

============================================
roq> q c test 2001:470:0000:0000:0000:0000:fe7c:60b2
============================================


DEBUG [Timer-0] (RoQBSONSerializer.java:81) - { "Hosts" : [ "2001:470:0000:0000:0000:0000:fe7c:60b2%2"]}
DEBUG [Thread-2] (MngtController.java:276) - Create Q request ...
DEBUG [Thread-2] (GlobalConfigurationStateClient.java:65) - Sending global state global config request...
DEBUG [Thread-4] (GlobalConfigurationManager.java:125) - Receiving request...2,1357665969070globalconfigclientState
DEBUG [Thread-4] (GlobalConfigurationManager.java:184) - Start analysing info code = 2
DEBUG [Thread-4] (GlobalConfigurationManager.java:191) - Recieveing init request from a client 
DEBUG [Thread-4] (GlobalConfigurationManager.java:196) - Sending back the topology - list of local host
 INFO [Thread-2] (GlobalConfigurationStateClient.java:83) - Getting configuration with 1 Host managers and 0 queues
DEBUG [Thread-2] (GlobalConfigurationStateClient.java:102) - Updating new local configuration
DEBUG [Thread-2] (GlobalConfigurationStateClient.java:128) - Connect to tcp://2001:470:0000:0000:0000:0000:fe7c:60b2%2:5100
ERROR [Thread-2] (GlobalConfigurationStateClient.java:134) - Error when connecting to host 2001:470:0000:0000:0000:0000:fe7c:60b2%2
org.zeromq.ZMQException: Invalid argument(0x16)
    at org.zeromq.ZMQ$Socket.connect(Native Method)
    at org.roqmessaging.management.GlobalConfigurationStateClient.updateLocalConfiguration(GlobalConfigurationStateClient.java:130)
    at org.roqmessaging.management.GlobalConfigurationStateClient.refreshConfiguration(GlobalConfigurationStateClient.java:85)
    at org.roqmessaging.management.LogicalQFactory.refreshTopology(LogicalQFactory.java:223)
    at org.roqmessaging.management.LogicalQFactory.createQueue(LogicalQFactory.java:74)
    at org.roqmessaging.management.server.MngtController.run(MngtController.java:287)
    at java.lang.Thread.run(Thread.java:722)
ERROR [Thread-2] (LogicalQFactory.java:122) - java.lang.IllegalStateException: the target address 2001:470:0000:0000:0000:0000:fe7c:60b2 is not registered as a node of the cluster (no Host manager running)
DEBUG [Thread-2] (RoQBSONSerializer.java:228) - { "RESULT" : 1101 , "COMMENT" : "ERROR when starting  queue, check logs of the logical queue factory"}
DEBUG [Thread-2] (MngtController.java:293) - Create queue name = test on 2001:470:0000:0000:0000:0000:fe7c:60b2
DEBUG [Management config publisher] (GlobalConfigTimer.java:70) - Sending Global configuration update to Management Subscribers ...
DEBUG [Thread-2] (MngtController.java:158) - Recieving Message in the update broadcast update channel
DEBUG [Thread-2] (MngtController.java:168) - Recieving update configuration message
DEBUG [Thread-2] (MngtServerStorage.java:408) - Updating configuration tables ...
DEBUG [Thread-2] (MngtServerStorage.java:382) - Get all queues
DEBUG [Thread-2] (MngtServerStorage.java:558) - Getting all hosts ...
DEBUG [Thread-2] (MngtServerStorage.java:565) - 2001:470:0000:0000:0000:0000:fe7c:60b2%2
```

**Comment by sskhiri** [comment]
The current solution just drops the content after the "%" in the address, however, this is not a good workaround. As described in http://lists.zeromq.org/pipermail/zeromq-dev/2011-August/012948.html the scope ID is important.
However, it does exist a patch in ZMQ, known as the Steven McCoy's Patch (http://lists.zeromq.org/pipermail/zeromq-dev/2011-August/012834.html). However in JZMQ, we cannot set the socket option as the method is private (as it is a native JNI method). As a result the JZMQ developer must expose a dedicated method for this option.
I have already send a mail in the ZMQ dev mailing list for that purpose.

**Comment by jbruggem** [comment]
Ok. Indeed the workaround does not help much. When I try to create a queue with a client, I get the following:

```
DEBUG [main] (GlobalConfigurationStateClient.java:65) - Sending global state global config request...
 INFO [main] (GlobalConfigurationStateClient.java:83) - Getting configuration with 1 Host managers and 0 queues
DEBUG [main] (GlobalConfigurationStateClient.java:102) - Updating new local configuration
DEBUG [main] (GlobalConfigurationStateClient.java:128) - Connect to tcp://2001:****:****:****:****:****:****:9fd6:5100
ERROR [main] (GlobalConfigurationStateClient.java:134) - Error when connecting to host 2001:****:****:****:****:****:****:9fd6
org.zeromq.ZMQException: Invalid argument(0x16)
    at org.zeromq.ZMQ$Socket.connect(Native Method)
    at org.roqmessaging.management.GlobalConfigurationStateClient.updateLocalConfiguration(GlobalConfigurationStateClient.java:130)
    at org.roqmessaging.management.GlobalConfigurationStateClient.refreshConfiguration(GlobalConfigurationStateClient.java:85)
    at org.roqmessaging.management.LogicalQFactory.refreshTopology(LogicalQFactory.java:223)
    at org.roqmessaging.management.LogicalQFactory.createQueue(LogicalQFactory.java:74)
    at com.euranova.testing.MainObject$.main(MainObject.scala:35)
    at com.euranova.testing.MainObject.main(MainObject.scala)
ERROR [main] (LogicalQFactory.java:122) - java.lang.IllegalStateException: the target address 2001:****:****:****:****:****:****:9fd6 is not registered as a node of the cluster (no Host manager running)
```

**Comment by sskhiri** [comment]
Waiting for the patch on JZMQ as explained here: http://www.mail-archive.com/zeromq-dev@lists.zeromq.org/msg17535.html
